###
GET http://localhost:3000/api/food/list-all
accept: application/json 
content-type: application/json

###
POST http://localhost:3000/api/food/add
accept: application/json 
content-type: application/json

{
    "name": "carne"
}

### REGISTER
POST http://localhost:3000/api/user/register
accept: application/json 
content-type: application/json

{
    "name": "pippo",
    "surname": "pluto",
    "username": "pippo3",
    "password": "admin",
    "email": "abc@fgh.it",
    "phoneNumber": "12345",
    "type": "test",
    "address": {
        "street": "vai abc",
        "civicNumber": "123/a",
        "city": "faenza",
        "coordinates": {
            "x": 123,
            "y": 456
        }
    }
}

### LOGIN
POST http://localhost:3000/api/user/login
accept: application/json
content-type: application/json

{
    "username": "admin",
    "password": "admin"
}

### UPDATE USER
POST http://localhost:3000/api/user/update
accept: application/json
content-type: application/json

{
    "_id": "6172e6a4df4d0325895749e2",
    "name": "pippo-updated",
    "surname": "pluto",
    "username": "pippo3",
    "password": "admin",
    "email": "abc@fgh.it",
    "phoneNumber": "12345",
    "type": "test",
    "address": {
        "street": "vai nuova",
        "civicNumber": "123/a",
        "city": "faenza",
        "coordinates": {
            "x": 123,
            "y": 456
        },
        "fake": "not to add"
    }
}
