### DONATION list all
POST http://localhost:3000/api/donation
accept: application/json 
content-type: application/json

{
    "filter": {
        "userId": "617ff2d461a8dc488e6e8bf3"
    }
}

### DONATION add
POST http://localhost:3000/api/donation
accept: application/json 
content-type: application/json

{
    "userId": "6183af3dabd629ea28db1cd9",
    "foods": [
        "ostriche",
        "champagne"
    ],
    "expirationDate": "2023-10-23",
    "additionaInformation": "bla bla bla",
    "address": {
        "street": "via nuova",
        "civicNumber": 13,
        "city": "faenza",
        "coordinates": {
            "x": 1.121282,
            "y": 2.385032
        }
    },
    "pickUpPeriod": [
        {
            "weekDay": "lun",
            "period": "afternoon"
            }
    ]
}

### DONATION delete
DELETE http://localhost:3000/api/donation
accept: application/json 
content-type: application/json

{
    "id": "6183b0048c3b83dbc6c74bcc"
}

### DONATION edit
POST http://localhost:3000/api/donation/edit
accept: application/json 
content-type: application/json

{
    "donationId": ""
}

### DONATION get chat
POST http://localhost:3000/api/donation/get-chat
accept: application/json 
content-type: application/json

{
    "donationId": "6183b0228c3b83dbc6c74bd4"
}

### DONATION get unread messages
POST http://localhost:3000/api/donation
accept: application/json 
content-type: application/json

{
    "filter": {
        "userId": "6183af3dabd629ea28db1cd9",
        "chat": {
            //seleziona gli array dove almeno un elemento matcha la condizione
            "$elemMatch": {
                "visualized": false
            }
        }
    },

    "projection": {
        //proiezione sui soli nodi della chat che matchano il filtro
        "chat.$": 1,
        "donationId": 1
    }
}