### DONATION list all
GET http://localhost:3000/api/donation/list-all
accept: application/json 
content-type: application/json

### DONATION add
POST http://localhost:3000/api/donation/add
accept: application/json 
content-type: application/json

{
    "user_id": "6172e6a4df4d0325895749e2",
    "chat":[
        {
            "user_id": "6172e6a4df4d0325895749e2",
            "text": "ciao",
            "visualized": true
            }
    ],
    "food_ids": [
        "617477acd81bbdee93050b51",
        "617477acd81bbdee93050b51"
    ],
    "expirationDate": "2023-10-23",
    "address": {
        "street": "via nuova",
        "civicNumber": 13,
        "city": "faenza",
        "coordinates": {
            "x": 1.121282,
            "y": 2.385032
        }
    },
    "pickUpPeriod": [
        {
            "weekDay": "lun",
            "period": "afternoon"
            }
    ]
}

### DONATION add message
POST http://localhost:3000/api/donation/add-message
accept: application/json 
content-type: application/json

{
    "donationId": "61752da118f0f36305767ec8",
    "chatNode": {
            "user_id": "6172e6a4df4d0325895749e2",
            "text": "ciao",
            "visualized": false
    }
}