### EVENT: add
POST http://localhost:3000/api/event/add
accept: application/json 
content-type: application/json

{
    "name": "evento 2",
    "address": {
        "street": "via nuova",
        "civicNumber": 13,
        "city": "faenza",
        "coordinates": {
            "x": 1.121282,
            "y": 2.385032
        }
    },
    "date": "2021-10-29",
    "ownerVolunteerId": "6172e6a4df4d0325895749e2"
}

### EVENT: list all
GET http://localhost:3000/api/event/list-all
accept: application/json 
content-type: application/json

### EVENT: find many
GET http://localhost:3000/api/event/list-all
accept: application/json 
content-type: application/json

{
    "filter": {
        "name": "evento abc"
    }
}

### EVENT: list all ordered
GET http://localhost:3000/api/event/list-all
accept: application/json 
content-type: application/json

{
    "sortBy": {
        "date": 1
    },
    "pageSize": 2,
    "page": 2
}