### FOOD: find all
POST http://localhost:3000/api/food/find
accept: application/json 
content-type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTc4NjY3YmZhYTcyMGEwNThmN2YyZTEiLCJpYXQiOjE2MzUzNjQwNzQsImV4cCI6MTYzNTM2NzY3NH0.9OYz7fPmtXA9kOKqejuHZzqLWQ9TjRVpyaDj1Z9FbR8
x-user-id: 6178667bfaa720a058f7f2e1

### FIND MANY
POST http://localhost:3000/api/food/find
accept: application/json 
content-type: application/json

{
    "sortBy": {
        "number": 1
    }
}

### FOOD: find food with quantity greter than 0
POST http://localhost:3000/api/food/find
accept: application/json 
content-type: application/json

{
    "filter": {
        "number": {
            "$gt": 0
        }
    }
}


### FOOD: find by id list
POST http://localhost:3000/api/food/find
accept: application/json 
content-type: application/json

{
    "filter": {
        "_id": [
            //"617477b5d81bbdee93050b54",
            "617477c5d81bbdee93050b5a",
            "617477b5d81bbdee93050b54"
        ]
    }
}

### ADD FOOD
### if exists an elem with same name and expiration date, will update it
#POST http://localhost:3000/api/food/add
POST http://localhost:3000/api/food/add-or-update
accept: application/json 
content-type: application/json

{
    //required fields
    "name": "pizza",
    "number": 1,
    "expirationDate": "2022-01-23" 

    //optional fields
    //"label": ["label1", "label2", "label3"]

}