### PACKS: list all
POST http://localhost:3000/api/pack/find
accept: application/json 
content-type: application/json

### PACKS: add
POST http://localhost:3000/api/pack/add
accept: application/json 
content-type: application/json

{
    "foodList": [
        {
            "_id": "617477acd81bbdee93050b51",
            "name": "pesce",
            "number": 2,
            "expirationDate": "2022-01-23",
            "labels": []
        },
        {
            "_id": "6187e1ec7d435f41efe7e357",
            "name": "pesce",
            "number": 2,
            "expirationDate": "2022-01-23",
            "labels": []
        }


    ],
    "deliveryVolunteerId": "6183af3dabd629ea28db1cd9",
    "familyId": "61868cc55b094054c03880c1"
}

### PACKS: set status to delivered
POST http://localhost:3000/api/pack/delivered
accept: application/json 
content-type: application/json

{
    "id": "61929aa5ceece835c6f92e58"
}