### REGISTER
POST http://localhost:3000/api/user/register
accept: application/json 
content-type: application/json

{
    "name": "utente",
    "surname": "fake",
    "password": "Password2021!",
    "email": "user@user.com",
    "phoneNumber": "12345",
    "address": {
        "street": "vai abc",
        "civicNumber": "123/a",
        "city": "faenza",
        "coordinates": {
            "x": 123,
            "y": 456
        }
    }
}

### LOGIN
POST http://localhost:3000/api/user/login
accept: application/json
content-type: application/json

{
    "email": "admin@admin.com",
    "password": "Password2021!"
}

### UPDATE USER
POST http://localhost:3000/api/user/update
accept: application/json
content-type: application/json

{
    "userId": "6172e6a4df4d0325895749e2",
    "name": "pippo-upd",
    "surname": "pluto-upd",
    "email": "abc@fgh.it",
    "phoneNumber": "12345",
    "type": "test",
    "address": {
        "street": "vai nuova",
        "civicNumber": "123/a",
        "city": "faenza",
        "coordinates": {
            "x": 123,
            "y": 456
        },
        "fake": "not to add"
    }
}

### UPDATE USER
POST http://localhost:3000/api/user/update
accept: application/json
content-type: application/json

{
    "userId": "6183af3dabd629ea28db1cd9",
    "name": "pippo-upd2",
    "surname": "pluto-upd2"
}

### UPGRADE USER
# passo l'id dell'utente da promuovere com epath parameter
# solo gli utenti trusted possono eleggere utenti user a volunteer
# la promozione a trusted può essere fatta solo manualmente
POST http://localhost:3000/api/user/upgrade
accept: application/json
content-type: application/json

{
    "userId": "6183af3dabd629ea28db1cd9"
}